{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-08T06:49:23.758Z"}
{"error":"Connection pool for operator-shard-00-01.smeax.mongodb.net:27017 was cleared because another operation failed with: \"connection <monitor> to 159.41.94.46:27017 timed out\"","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-08T16:59:40.274Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-08T22:17:28.267Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-08T22:17:45.360Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-08T22:20:05.089Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-09T17:01:14.013Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-12T02:21:43.285Z"}
{"error":"Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-13T21:41:18.572Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-13T21:46:34.042Z"}
{"error":"Server selection timed out after 5000 ms","level":"error","message":"MongoDB connection failed","timestamp":"2025-04-13T21:46:52.324Z"}
{"code":"insufficient_quota","error":{"code":"insufficient_quota","message":"You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","param":null,"type":"insufficient_quota"},"headers":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"93093fe4bffe93c9-JNB","connection":"keep-alive","content-length":"337","content-type":"application/json; charset=utf-8","date":"Tue, 15 Apr 2025 06:05:09 GMT","server":"cloudflare","set-cookie":"__cf_bm=jutK.DjT9mA7EoKo68Jza0xPQOTuDicnlOMJDg6gavA-1744697109-1.0.1.1-j6FdEPfRfObJ2tb6Cx6xutFpPeTIb0naYOfSQeo3NpnCrrV5WwWx.KRB9U0Hr.fWec8rauYTuUztU58sxHqSqpzz2.u6hZBrpVyAWLAAGYE; path=/; expires=Tue, 15-Apr-25 06:35:09 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=_MEidPBTEOLVEy_BAKWC.COS3XwNehHntaeZcuFUifM-1744697109494-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","vary":"Origin","x-content-type-options":"nosniff","x-request-id":"req_77aedf0b4108777b5791415c160e680e"},"level":"error","message":"Classification error, defaulting to task 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","param":null,"request_id":"req_77aedf0b4108777b5791415c160e680e","stack":"Error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.\n    at APIError.generate (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/error.mjs:59:20)\n    at OpenAI.makeStatusError (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/core.mjs:293:25)\n    at OpenAI.makeRequest (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/core.mjs:337:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async openaiClassifyPrompt (file:///C:/Users/cosyc/OPERATOR-stable/server.js:2246:26)\n    at async file:///C:/Users/cosyc/OPERATOR-stable/server.js:2282:22","status":429,"timestamp":"2025-04-15T06:05:16.007Z","type":"insufficient_quota"}
{"code":"insufficient_quota","error":{"code":"insufficient_quota","message":"You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","param":null,"type":"insufficient_quota"},"headers":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"930d5201fd1593d0-JNB","connection":"keep-alive","content-length":"337","content-type":"application/json; charset=utf-8","date":"Tue, 15 Apr 2025 17:56:34 GMT","server":"cloudflare","set-cookie":"__cf_bm=JznAoGHuj6j4lATRzmHDMfTyxsyTZEYT_024z_gTeSY-1744739794-1.0.1.1-waKU9J9BpJQ7xNb5T1la8Q7xUAOZmo1x7pf10qdS09yZn4kM0ajeMTjxfU8OwfjNomkT0mJNJ3RIHjSNu67vTEP4InfzamDhqNtix14Bcs0; path=/; expires=Tue, 15-Apr-25 18:26:34 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=18FJuaMNJx8.wjtWJB81Gz_9S.rL.ug3lKI5s4TWWLU-1744739794478-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","vary":"Origin","x-content-type-options":"nosniff","x-request-id":"req_70057e2c5ec6c6f9090904c1c00eb99b"},"level":"error","message":"Classification error, defaulting to task 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","param":null,"request_id":"req_70057e2c5ec6c6f9090904c1c00eb99b","stack":"Error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.\n    at APIError.generate (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/error.mjs:59:20)\n    at OpenAI.makeStatusError (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/core.mjs:293:25)\n    at OpenAI.makeRequest (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/core.mjs:337:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async openaiClassifyPrompt (file:///C:/Users/cosyc/OPERATOR-stable/server.js:2244:26)\n    at async file:///C:/Users/cosyc/OPERATOR-stable/server.js:2279:22","status":429,"timestamp":"2025-04-15T17:56:39.366Z","type":"insufficient_quota"}
{"code":"invalid_api_key","error":{"code":"invalid_api_key","message":"Incorrect API key provided: shf_xdnT**************************unHP. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"},"headers":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"930e2ce7c99673b9-JNB","connection":"keep-alive","content-length":"288","content-type":"application/json; charset=utf-8","date":"Tue, 15 Apr 2025 20:26:00 GMT","server":"cloudflare","set-cookie":"__cf_bm=n1ksZZkUeDhMICizAbiDr_tyy0MCcZzZ5IGmXhSlwfg-1744748760-1.0.1.1-F0Dj2nV_2BbYjO5pXIO6iEgt7WffM9caNh4MIRogR4glhl0OdigC3pXSK1bRD1Gd1W18dBszKEFeChb8TBGv7BSEMCtQJLoCZJFDE0_foUY; path=/; expires=Tue, 15-Apr-25 20:56:00 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=fNr_EaLilF3.h0H.tWYUn99EUKJoK0cfxrFbYHyZ2B4-1744748760643-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","vary":"Origin","x-content-type-options":"nosniff","x-request-id":"req_0d5c2829a93cabdffde224b6b476b706"},"level":"error","message":"Classification error, defaulting to task 401 Incorrect API key provided: shf_xdnT**************************unHP. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"request_id":"req_0d5c2829a93cabdffde224b6b476b706","stack":"Error: 401 Incorrect API key provided: shf_xdnT**************************unHP. You can find your API key at https://platform.openai.com/account/api-keys.\n    at APIError.generate (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/error.mjs:44:20)\n    at OpenAI.makeStatusError (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/core.mjs:293:25)\n    at OpenAI.makeRequest (file:///C:/Users/cosyc/OPERATOR-stable/node_modules/openai/core.mjs:337:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async openaiClassifyPrompt (file:///C:/Users/cosyc/OPERATOR-stable/server.js:2212:26)\n    at async file:///C:/Users/cosyc/OPERATOR-stable/server.js:2248:22","status":401,"timestamp":"2025-04-15T20:26:06.388Z","type":"invalid_request_error"}
